### ISSUE TITLE
Italics are applied to technical names in commands

### ISSUE THREAD

**Issue by Happy1speed** [der-fruhling-entertainment/markit#1]
If you have an item like minecraft:iron_sword it will show up as minecraft:iron _sword_ 
(without the space in between iron and sword)
It would be nice to be able to change italics to something else and/or have a config option for it.

**Comment by der-fruhling** [comment]
Should be fixed in v0.1.1. Thanks for reporting this.

**Comment by Happy1speed** [comment]
Great!
